"""Boss art v2 -> js/art/bosses.js. Each boss lives in tools/boss_<name>.py with a build() returning its frames as rows of palette letters."""
import json, os, sys, importlib
sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
NAMES = ['beetle', 'moth', 'wyrm', 'jelly', 'heart']

def main():
    out = {}
    for n in NAMES:
        try: m = importlib.import_module('boss_' + n)
        except ImportError: continue
        out[n] = m.build()
    path = os.path.join(os.path.dirname(os.path.abspath(__file__)), '..', 'js', 'art', 'bosses.js')
    src = "/* GENERATED by tools/boss_gen2.py: boss sprites (beetle, moth, wyrm, jelly, heart). */\n(function (G) {\n  G.art = G.art || {};\n  G.art.bosses = " + json.dumps(out, separators=(',', ':')) + ";\n})((window.SGS = window.SGS || {}));\n"
    open(path, 'w', encoding='utf-8').write(src)
    print('wrote', len(src), 'bosses', list(out))

if __name__ == '__main__':
    main()
