"""Zone 2 boss: the Rimewing Sovereign, a front-facing ice moth, 140 x 100 (symmetric, no mirroring) -> js/art/boss2.js. Compile with the 'teal' key set."""
import json, math, os
Wd, Hd = 140, 100
CX = 70

def blank(): return [['.'] * Wd for _ in range(Hd)]
def put(g, x, y, c):
    if 0 <= x < Wd and 0 <= y < Hd: g[y][x] = c
def line(g, x0, y0, x1, y1, c, t=1):
    n = max(abs(x1 - x0), abs(y1 - y0), 1)
    for i in range(n + 1):
        x = round(x0 + (x1 - x0) * i / n); y = round(y0 + (y1 - y0) * i / n)
        for dx in range(t):
            for dy in range(t): put(g, x + dx, y + dy, c)
def inside(pts, x, y):
    c = False; j = len(pts) - 1
    for i in range(len(pts)):
        xi, yi = pts[i]; xj, yj = pts[j]
        if (yi > y) != (yj > y) and x < (xj - xi) * (y - yi) / (yj - yi + 1e-9) + xi: c = not c
        j = i
    return c
def tri_fill(g, a, b, c, col):
    pts = [a, b, c]
    for y in range(min(p[1] for p in pts), max(p[1] for p in pts) + 1):
        for x in range(min(p[0] for p in pts), max(p[0] for p in pts) + 1):
            if inside(pts, x + 0.5, y + 0.5): put(g, x, y, col)
def shade(x, y, cx, cy, rx, ry, bias=0.62):
    nx, ny = (x - cx) / rx, (y - cy) / ry
    z = math.sqrt(max(0.0, 1 - nx * nx - ny * ny)); l = -0.5 * nx - 0.55 * ny + bias * z
    return '4' if l > 1.0 else '3' if l > 0.7 else '2' if l > 0.36 else '1'

def wing(g, root, verts, tones, side):
    """fan of facets from the root; side=-1 left, +1 right (mirrored about CX)"""
    m = (lambda p: (2 * CX - 1 - p[0], p[1])) if side > 0 else (lambda p: p)
    r = m(root); vs = [m(v) for v in verts]
    for i in range(len(vs) - 1):
        tri_fill(g, r, vs[i], vs[i + 1], tones[i % len(tones)] if side < 0 else tones[(i + 1) % len(tones)])
    for v in vs:
        line(g, r[0], r[1], v[0], v[1], 'E' if side < 0 else 'e')
    for i in range(len(vs) - 1):
        line(g, vs[i][0], vs[i][1], vs[i + 1][0], vs[i + 1][1], 'h' if side < 0 else 'E')
    return r, vs

def frame(wing_up=0, folded=False, glow=False, core=False, flick=False, droop=0):
    g = blank()
    dy = [16, 0, -16][wing_up + 1] if not folded else 26
    wy = droop
    if folded:
        up = [(52, 58 + wy), (36, 52 + wy), (26, 82 + wy), (44, 94 + wy)]; lo = [(54, 66 + wy), (42, 88 + wy), (56, 98 + wy)]
    else:
        up = [(58, 46), (30, 20 + dy), (4, 6 + dy), (2, 36 + dy // 2), (22, 56 + dy // 3), (50, 60)]
        lo = [(58, 58), (28, 70 + dy // 2), (16, 94 + dy // 3), (44, 96 + dy // 4), (56, 78)]
    for side in (-1, 1):
        wing(g, (60, 52), up, ['3', '2', '4', '3', '2'], side)
        wing(g, (60, 58), lo, ['2', '3', '2', '4'], side)
    # abdomen, thorax, head (shaded ellipses)
    for (cx, cy, rx, ry) in ((CX, 82.0, 8.0, 14.0), (CX, 56.0, 12.0, 17.0), (CX, 34.0, 10.0, 9.0)):
        for y in range(Hd):
            for x in range(Wd):
                if ((x + 0.5 - cx) / rx) ** 2 + ((y + 0.5 - cy) / ry) ** 2 <= 1: g[y][x] = shade(x, y, cx, cy, rx, ry)
    for y in range(66, 94, 4): line(g, CX - 6, y, CX + 5, y, '1')          # abdomen segments
    for (x, y) in ((CX - 5, 33), (CX + 4, 33)):                             # eyes
        for dx in range(3):
            for dy in range(2): put(g, x + dx, y + dy, 'h' if (dx + dy) % 2 == 0 or glow else 'E')
    line(g, CX - 5, 26, CX - 18, 6, 'o', 1); line(g, CX + 4, 26, CX + 17, 6, 'o', 1)      # antennae
    for (x, y) in ((CX - 18, 5), (CX + 17, 5)): put(g, x, y, 'h')
    if glow:
        for dx in range(-3, 4): put(g, CX + dx, 41, 'h')
    # core: a gem on the thorax, hidden by two dark plates until exposed
    cy = 56
    for y in range(cy - 7, cy + 8):
        for x in range(CX - 7, CX + 8):
            d = (x + 0.5 - CX) ** 2 + (y + 0.5 - cy) ** 2
            if d <= 49:
                if core: g[y][x] = ('h' if flick else 'E') if d < 12 else 'E' if d < 24 else 'e' if d < 38 else 'g'
                else: g[y][x] = '1' if d < 40 else 'o'
    if not core:
        line(g, CX - 6, cy, CX + 5, cy, 'o', 1)
    out = [r[:] for r in g]
    for y in range(Hd):
        for x in range(Wd):
            if g[y][x] == '.':
                for dx, dy in ((1, 0), (-1, 0), (0, 1), (0, -1)):
                    xx, yy = x + dx, y + dy
                    if 0 <= xx < Wd and 0 <= yy < Hd and g[yy][xx] != '.': out[y][x] = 'o'; break
    return [''.join(r) for r in out]

if __name__ == '__main__':
    out = {'fly': [frame(1), frame(0), frame(-1), frame(0)], 'shoot': [frame(0, glow=True), frame(1, glow=True)], 'dive': frame(0, folded=True, glow=True),
           'stun': [frame(-1, core=True, droop=0, folded=False), frame(-1, core=True, flick=True)], 'dead': frame(-1, core=True, flick=True)}
    path = os.path.join(os.path.dirname(os.path.abspath(__file__)), '..', 'js', 'art', 'boss2.js')
    src = "/* GENERATED by tools/boss2_gen.py: the Rimewing Sovereign (140x100 frames, symmetric). */\n(function (G) {\n  G.art = G.art || {};\n  G.art.boss2 = " + json.dumps(out, separators=(',', ':')) + ";\n})((window.SGS = window.SGS || {}));\n"
    open(path, 'w', encoding='utf-8').write(src)
    print('wrote', len(src))
