r"""Builds js/rooms/zone1..5.js from the zoneN_gen.py room definitions and places the zones on the world map as a serpentine: zone 1 runs east, zone 2 runs west
(its rooms are mirrored), zone 3 east, zone 4 west, zone 5 east, so each zone's lift drops straight down onto the next zone's gate."""
import importlib, json, os, sys
HERE = os.path.dirname(os.path.abspath(__file__))
sys.path.insert(0, HERE)
from room_kit import BS

# per zone: mirror the rooms (flip), world width used for the mirror, and cell offsets
LAYOUT = {1: dict(flip=False, W=0, ox=0, oy=0), 2: dict(flip=True, W=16, ox=0, oy=0), 3: dict(flip=False, W=0, ox=1, oy=1),
          4: dict(flip=True, W=18, ox=0, oy=2), 5: dict(flip=False, W=0, ox=3, oy=3)}

def mirror_def(d):
    tr = {'/': BS, BS: '/'}
    w = len(d['map'][0])
    d['map'] = [''.join(tr.get(c, c) for c in row[::-1]) for row in d['map']]
    for dr in d['doors']: dr['side'] = 'R' if dr['side'] == 'L' else 'L'
    for it in d['items']: it['tx'] = w - 1 - it['tx']
    for st in d['stations']: st['tx'] = w - 1 - st['tx']
    assert not d['movers'] and not d['decor'], ('cannot mirror a room with movers or decor', d['id'])

def main():
    for z in (1, 2, 3, 4, 5):
        m = importlib.import_module('zone%d_gen' % z)
        rooms = m.ROOMS if z == 1 else m.Z
        L = LAYOUT[z]; out = {}
        for r in rooms:
            d = r.emit(); cw = -(-len(d['map'][0]) // 30)
            if L['flip']: mirror_def(d); d['mx'] = L['W'] - cw - d['mx']
            d['mx'] += L['ox']; d['my'] += L['oy']
            out[d['id']] = d
        path = os.path.join(HERE, '..', 'js', 'rooms', 'zone%d.js' % z)
        src = "/* GENERATED by tools/build_world.py from tools/zone%d_gen.py: zone %d room layouts, doors, items, stations and moving platforms. */\n(function (G) {\n  G.rooms = G.rooms || {};\n  Object.assign(G.rooms, " % (z, z) + json.dumps(out, separators=(',', ':')) + ");\n})((window.SGS = window.SGS || {}));\n"
        open(path, 'w', encoding='utf-8').write(src)
        print('zone', z, 'rooms', len(out), 'bytes', len(src))

if __name__ == '__main__':
    main()
