"""Zone 4 art -> js/art/zone4foes.js: reactor jellyfish (3 frames) and the Abyssal Jelly boss bell (closed / open core). Compile with 'teal' (digits) + energy letters."""
import json, math, os

def blank(w, h): return [['.'] * w for _ in range(h)]
def put(g, x, y, c):
    if 0 <= y < len(g) and 0 <= x < len(g[0]): g[y][x] = c
def shade(x, y, cx, cy, rx, ry, bias=0.62):
    nx, ny = (x - cx) / rx, (y - cy) / ry
    z = math.sqrt(max(0.0, 1 - nx * nx - ny * ny)); l = -0.5 * nx - 0.55 * ny + bias * z
    return '4' if l > 1.0 else '3' if l > 0.7 else '2' if l > 0.36 else '1'
def outline(g):
    h, w = len(g), len(g[0]); out = [r[:] for r in g]
    for y in range(h):
        for x in range(w):
            if g[y][x] == '.':
                for dx, dy in ((1, 0), (-1, 0), (0, 1), (0, -1)):
                    xx, yy = x + dx, y + dy
                    if 0 <= xx < w and 0 <= yy < h and g[yy][xx] != '.': out[y][x] = 'o'; break
    return [''.join(r) for r in out]

def jelly(f):
    """reactor jelly 24 x 30: translucent bell with glowing core and three trailing tentacles; f pulses the bell"""
    W, H = 24, 30; g = blank(W, H); sq = [0, 2, 0][f]
    cx, cy, rx, ry = 12.0, 11.0, 10.0 - sq * 0.5, 9.0 + (1 if f == 1 else 0)
    for y in range(H):
        for x in range(W):
            nx, ny = (x - cx) / rx, (y - cy) / ry
            if nx * nx + ny * ny <= 1 and y <= cy + 4: g[y][x] = shade(x, y, cx, cy, rx, ry, 0.7)
    for x in range(4, 20):
        if g[int(cy) + 4][x] != '.': g[int(cy) + 4][x] = '1'
    for y in range(int(cy) - 2, int(cy) + 3):
        for x in range(int(cx) - 3, int(cx) + 4):
            d = (x - cx) ** 2 + (y - cy) ** 2
            if d <= 9: g[y][x] = 'h' if d < 2 else 'E' if d < 5 else 'e'
    for k, tx in enumerate((6, 12, 18)):
        for y in range(int(cy) + 5, H):
            sw = int(round(math.sin(y * 0.55 + k * 2.0 + f * 2.1) * 1.8)); put(g, tx + sw, y, '3' if y % 3 else '2')
    return outline(g)

def boss_bell(open_):
    """Abyssal Jelly bell, 112 x 78: ribbed dome, scalloped skirt; open_ shows the glowing core"""
    W, H = 112, 78; g = blank(W, H); cx, cy, rx, ry = 56.0, 44.0, 50.0, 40.0
    for y in range(H):
        for x in range(W):
            nx, ny = (x - cx) / rx, (y - cy) / ry
            if nx * nx + ny * ny <= 1 and y <= cy + 14: g[y][x] = shade(x, y, cx, cy, rx, ry, 0.72)
    for k in range(-5, 6):
        for y in range(6, int(cy) + 14):
            x = int(cx + k * 8.2 * (1 - 0.35 * ((y - 6) / 60.0)) * 0.9 + (k * (y - 6) * 0.02))
            if 0 <= x < W and g[y][x] != '.': g[y][x] = '1' if y % 4 else '2'
    for x in range(8, 104):
        d = int(4 + 3 * abs(math.sin(x * 0.34)))
        for y in range(int(cy) + 14, int(cy) + 14 + d):
            if y < H and abs((x - cx) / (rx * 0.98)) <= 1: g[y][x] = '2' if y == int(cy) + 14 else '3' if (x // 4) % 2 else '4'
    ccx, ccy = 56, 46
    for y in range(H):
        for x in range(W):
            d = ((x - ccx) / (20.0 if open_ else 12.0)) ** 2 + ((y - ccy) / (16.0 if open_ else 10.0)) ** 2
            if d <= 1:
                if open_: g[y][x] = 'h' if d < 0.12 else 'E' if d < 0.4 else 'e' if d < 0.75 else 'g'
                else: g[y][x] = '1' if d < 0.7 else 'o'
    if not open_:
        for k in range(6): put(g, ccx - 5 + k * 2, ccy, 'o'); put(g, ccx - 5 + k * 2, ccy + 1, 'o')
    return outline(g)

if __name__ == '__main__':
    out = {'jelly': [jelly(i) for i in range(3)], 'bell': [boss_bell(False), boss_bell(True)]}
    path = os.path.join(os.path.dirname(os.path.abspath(__file__)), '..', 'js', 'art', 'zone4foes.js')
    src = "/* GENERATED by tools/enemy_gen4.py: zone 4 jelly and Abyssal Jelly art. */\n(function (G) {\n  G.art = G.art || {};\n  G.art.zone4foes = " + json.dumps(out, separators=(',', ':')) + ";\n})((window.SGS = window.SGS || {}));\n"
    open(path, 'w', encoding='utf-8').write(src)
    print('wrote', len(src))
