"""Zone 5 art -> js/art/zone5foes.js: egg spawner (2 frames), shield node (2), Hive Core heart (closed / open / open+flicker). Compile with 'visor' (digits) + gold/energy letters."""
import json, math, os

def blank(w, h): return [['.'] * w for _ in range(h)]
def put(g, x, y, c):
    if 0 <= y < len(g) and 0 <= x < len(g[0]): g[y][x] = c
def line(g, x0, y0, x1, y1, c, t=1):
    n = max(abs(x1 - x0), abs(y1 - y0), 1)
    for i in range(n + 1):
        x = round(x0 + (x1 - x0) * i / n); y = round(y0 + (y1 - y0) * i / n)
        for dx in range(t):
            for dy in range(t): put(g, x + dx, y + dy, c)
def shade(x, y, cx, cy, rx, ry, bias=0.62):
    nx, ny = (x - cx) / rx, (y - cy) / ry
    z = math.sqrt(max(0.0, 1 - nx * nx - ny * ny)); l = -0.5 * nx - 0.55 * ny + bias * z
    return '4' if l > 1.0 else '3' if l > 0.7 else '2' if l > 0.36 else '1'
def outline(g):
    h, w = len(g), len(g[0]); out = [r[:] for r in g]
    for y in range(h):
        for x in range(w):
            if g[y][x] == '.':
                for dx, dy in ((1, 0), (-1, 0), (0, 1), (0, -1)):
                    xx, yy = x + dx, y + dy
                    if 0 <= xx < w and 0 <= yy < h and g[yy][xx] != '.': out[y][x] = 'o'; break
    return [''.join(r) for r in out]

def egg(f):
    """egg spawner 26 x 32: ribbed sac on a base, a glowing slit that widens when it is about to hatch"""
    W, H = 26, 32; g = blank(W, H)
    for y in range(H):
        for x in range(W):
            nx, ny = (x - 13.0) / 11.0, (y - 15.0) / 14.0
            if nx * nx + ny * ny <= 1 and y < 28: g[y][x] = shade(x, y, 13.0, 15.0, 11.0, 14.0)
    for y in range(26, 32):
        for x in range(2, 24):
            if abs(x - 13) <= 11 - (y - 26) * 0.4: g[y][x] = '1' if y > 27 else '2'
    for k in range(-2, 3):
        for y in range(4, 26):
            x = int(13 + k * 4.2 * (1 - abs((y - 15) / 18.0) ** 2))
            if g[y][x] != '.': g[y][x] = '1'
    w = 1 if f == 0 else 3
    for y in range(11, 20):
        for dx in range(-w, w + 1): put(g, 13 + dx, y, 'Y' if abs(dx) < w else 'y')
    for y in (10, 20): put(g, 13, y, 'k')
    return outline(g)

def node(f):
    """shield node 34 x 34: a thorny sac; f 1 = flashing"""
    W, H = 34, 34; g = blank(W, H)
    for y in range(H):
        for x in range(W):
            nx, ny = (x - 17.0) / 12.0, (y - 17.0) / 12.0
            if nx * nx + ny * ny <= 1: g[y][x] = shade(x, y, 17.0, 17.0, 12.0, 12.0)
    for k in range(8):
        a = k * math.pi / 4 + 0.2; line(g, int(17 + math.cos(a) * 11), int(17 + math.sin(a) * 11), int(17 + math.cos(a) * 16), int(17 + math.sin(a) * 16), '4' if k % 2 else '3', 2)
    for y in range(12, 23):
        for x in range(12, 23):
            d = (x - 17) ** 2 + (y - 17) ** 2
            if d <= 20: g[y][x] = ('w' if f else 'Y') if d < 6 else 'y' if d < 13 else 'k'
    return outline(g)

def heart(state):
    """Hive Core heart 128 x 128: throbbing organ ringed by thorns; state 0 sealed, 1 open (core glowing), 2 open + bright"""
    W, H = 128, 128; g = blank(W, H); cx, cy = 64.0, 66.0; rx, ry = 52.0, 54.0
    for y in range(H):
        for x in range(W):
            nx, ny = (x - cx) / rx, (y - cy) / ry
            if nx * nx + ny * ny <= 1: g[y][x] = shade(x, y, cx, cy, rx, ry, 0.7)
    for k in range(7):                                  # veins
        a = -math.pi / 2 + (k - 3) * 0.42
        px, py = cx, cy
        for s in range(40):
            px += math.cos(a + math.sin(s * 0.3 + k) * 0.25) * 1.4; py += math.sin(a + math.sin(s * 0.3 + k) * 0.25) * 1.4
            if (px - cx) ** 2 / rx ** 2 + (py - cy) ** 2 / ry ** 2 < 0.92: put(g, int(px), int(py), '1'); put(g, int(px) + 1, int(py), '2')
    for k in range(14):                                 # thorns
        a = k * 2 * math.pi / 14; line(g, int(cx + math.cos(a) * rx * 0.96), int(cy + math.sin(a) * ry * 0.96), int(cx + math.cos(a) * (rx + 12)), int(cy + math.sin(a) * (ry + 12)), '3', 3)
    for y in range(H):
        for x in range(W):
            d = ((x - cx) / (20.0 if state else 13.0)) ** 2 + ((y - cy) / (22.0 if state else 14.0)) ** 2
            if d <= 1:
                if state: g[y][x] = ('w' if state == 2 else 'Y') if d < 0.2 else 'Y' if d < 0.5 else 'y' if d < 0.8 else 'k'
                else: g[y][x] = '1' if d < 0.75 else 'o'
    if not state:
        for k in range(8): put(g, int(cx) - 7 + k * 2, int(cy), 'o'); put(g, int(cx) - 7 + k * 2, int(cy) + 1, 'o')
    return outline(g)

if __name__ == '__main__':
    out = {'egg': [egg(0), egg(1)], 'node': [node(0), node(1)], 'heart': [heart(0), heart(1), heart(2)]}
    path = os.path.join(os.path.dirname(os.path.abspath(__file__)), '..', 'js', 'art', 'zone5foes.js')
    src = "/* GENERATED by tools/enemy_gen5.py: zone 5 egg spawner, shield node and Hive Core heart. */\n(function (G) {\n  G.art = G.art || {};\n  G.art.zone5foes = " + json.dumps(out, separators=(',', ':')) + ";\n})((window.SGS = window.SGS || {}));\n"
    open(path, 'w', encoding='utf-8').write(src)
    print('wrote', len(src))
