"""Zone 1 enemies -> js/art/zone1foes.js. Grids are authored short and padded to a fixed width; armor letters o,1-4 take the creature's colour ramp (crimson / teal) at compile time."""
import json, os

def pad(rows, w):
    out = []
    for r in rows:
        assert len(r) <= w, (r, len(r), w)
        out.append(r + '.' * (w - len(r)))
    return out

# --- shell crawler: armoured beetle, faces right, 16 x 13 -------------------------------------------------
SHELL = [
    "",
    "",
    "....ooooo",
    "..oo444433oo",
    ".o4443333322o",
    "o444333322221o...oo",
    "o4433332222211oooo4o",
    "o3333222221111o44oYo",
    ".o3322221111o.o44oo",
    "..o22221111o..ooo",
    "...oooooooo",
]
SHELL = pad(SHELL, 20)
def crawler(phase):
    rows = [list(r) for r in SHELL]
    # armour plate seams (dark groove with a lit lip on its left), then a bigger eye
    for x in (6, 10):
        for y in range(3, 10):
            if rows[y][x] not in 'o.':
                rows[y][x] = '1'
                if rows[y][x - 1] in '234': rows[y][x - 1] = '4' if rows[y][x - 1] != '4' else '4'
    rows[7][18] = 'W'; rows[6][18] = 'Y'; rows[6][17] = 'o'
    rows[8][17] = 'w'; rows[9][16] = 'w'
    rows += [list('.' * 20) for _ in range(4)]
    sh = [(-1, 0, 1), (0, 0, 0), (1, 0, -1), (0, 0, 0)][phase]
    lift = [(0, 1, 0), (0, 0, 0), (1, 0, 0), (0, 0, 0)][phase]
    for n, x in enumerate((4, 8, 13)):
        up = lift[n]
        rows[11][x] = 'o'; rows[11][x + 1] = 'o'
        rows[12 - up][x + sh[n]] = 'o'; rows[12 - up][x + sh[n] + 1] = '1'
        rows[13 - up][x + sh[n] - 1] = '1'; rows[13 - up][x + sh[n]] = '1'
    return [''.join(r) for r in rows]

# --- glow-moth: hovering flyer, 20 x 16, wings flap through 4 frames --------------------------------------
MOTH_BODY = [
    "........o44o",
    ".......o4332o",
    ".......o3322o",
    "......oo3221oo",
    "......o322 11o".replace(' ', ''),
    ".......o2211o",
    ".......oo11oo",
    "........oYYo",
    ".........oo",
]
WING = {  # (row, x0, x1) for the left wing, mirrored to the right; rows count from the top of the sprite
    'up':   [(0, 1, 2), (1, 1, 4), (2, 2, 6), (3, 3, 7), (4, 4, 8), (5, 5, 8)],
    'mid':  [(3, 0, 3), (4, 0, 7), (5, 1, 8), (6, 2, 8), (7, 4, 8)],
    'down': [(6, 0, 1), (7, 0, 3), (8, 1, 5), (9, 2, 7), (10, 3, 8), (5, 6, 8)],
}
def moth(kind):
    W, H = 20, 14
    g = [['.'] * W for _ in range(H)]
    by = 2 if kind != 'down' else 1
    for i, r in enumerate(pad(MOTH_BODY, W)):
        for x, c in enumerate(r):
            if c != '.' and 0 <= by + i < H: g[by + i][x] = c
    for (y, x0, x1) in WING[kind]:
        for x in range(x0, x1 + 1):
            c = 'h' if x == x0 else 'e' if x < x1 - 1 else 'E'
            if y == min(r for r, _, _ in WING[kind]): c = 'h'
            for xx in (x, W - 1 - x):
                if g[y][xx] == '.': g[y][xx] = c
    return [''.join(r) for r in g]
MOTH_FRAMES = ['up', 'mid', 'down', 'mid']

# --- spore pod: rooted turret, 16 x 24, closed / open mouth ---------------------------------------------
def pod(opened):
    rows = [
        "......ooo.......",
        ".....o444o......",
        "....o44332o.....",
        "...o4433322o....",
        "...o4333222o....",
        "...o3322211o....",
        "....o22211o.....",
        ".....o111o......",
        "......ooo.......",
    ]
    if opened:
        rows[2] = "....o4Yw32o....."; rows[3] = "...o4YYw322o...."
        rows[4] = "...o4wwY2222o..."; rows[5] = "...o3YYY2211o..."
    rows = rows + [
        "......DCB.......",
        "......DCB.......",
        ".....DDCB.......",
        "..E.EDCCBE.E....",
        "..DEDDCCBDED....",
        "...DDCCCBBD.....",
        "..B.CDCBBC.B....",
        ".BBBBCCBBBBBB...",
        "BCDBBBBBBBBDCB..",
        "11BCB1BB1BCB11..",
    ]
    return pad(rows, 16)

if __name__ == '__main__':
    out = {'crawler': [crawler(i) for i in range(4)], 'moth': [moth(k) for k in MOTH_FRAMES], 'pod': [pod(0), pod(1)]}
    path = os.path.join(os.path.dirname(os.path.abspath(__file__)), '..', 'js', 'art', 'zone1foes.js')
    src = "/* GENERATED by tools/enemy_gen.py: zone 1 enemy frame grids (armor letters recolour per creature). */\n(function (G) {\n  G.art = G.art || {};\n  G.art.zone1foes = " + json.dumps(out, separators=(',', ':')) + ";\n})((window.SGS = window.SGS || {}));\n"
    open(path, 'w', encoding='utf-8').write(src)
    print('wrote', len(src))
