"""Zone 2 enemies -> js/art/zone2foes.js: frost wisp (hover), frostling (hopper), shard turret. Armor letters o,1-4 take the 'teal' ramp; E/e/h glow."""
import json, math, os

def blank(w, h): return [['.'] * w for _ in range(h)]
def put(g, x, y, c):
    if 0 <= y < len(g) and 0 <= x < len(g[0]): g[y][x] = c
def line(g, x0, y0, x1, y1, c, t=1):
    n = max(abs(x1 - x0), abs(y1 - y0), 1)
    for i in range(n + 1):
        x = round(x0 + (x1 - x0) * i / n); y = round(y0 + (y1 - y0) * i / n)
        for dx in range(t):
            for dy in range(t): put(g, x + dx, y + dy, c)
def shade(x, y, cx, cy, rx, ry, bias=0.62):
    nx, ny = (x - cx) / rx, (y - cy) / ry
    z = math.sqrt(max(0.0, 1 - nx * nx - ny * ny)); l = -0.5 * nx - 0.55 * ny + bias * z
    return '4' if l > 1.0 else '3' if l > 0.7 else '2' if l > 0.36 else '1'
def outline(g, keep='ohHEeg'):
    h, w = len(g), len(g[0]); out = [r[:] for r in g]
    for y in range(h):
        for x in range(w):
            if g[y][x] == '.':
                for dx, dy in ((1, 0), (-1, 0), (0, 1), (0, -1)):
                    xx, yy = x + dx, y + dy
                    if 0 <= xx < w and 0 <= yy < h and g[yy][xx] != '.': out[y][x] = 'o'; break
    return [''.join(r) for r in out]

def wisp(phase):
    """frost wisp 20 x 22: glowing core in a crystal shell, orbiting sparks, a wavering tail"""
    W, H = 20, 22; g = blank(W, H); cx, cy = 10.0, 9.0; r = [6.4, 7.0, 6.4][phase]
    for y in range(H):
        for x in range(W):
            if (x - cx) ** 2 + (y - cy) ** 2 <= r * r: g[y][x] = shade(x, y, cx, cy, r, r, 0.7)
    for y in range(int(cy) - 3, int(cy) + 4):
        for x in range(int(cx) - 3, int(cx) + 4):
            d = (x - cx) ** 2 + (y - cy) ** 2
            if d <= 9: g[y][x] = 'h' if d < 2 else 'E' if d < 5 else 'e'
    for k in range(7):                   # tail
        sw = int(round(math.sin(k * 0.9 + phase * 2.1) * 1.6)); put(g, 10 + sw, 16 + k // 2 * 1 + (0 if k < 4 else 1), 'e' if k < 3 else 'g'); put(g, 9 + sw, 15 + k // 2, '2')
    for (a, rr) in ((phase * 2.1, 9.0), (phase * 2.1 + 3.14, 9.0)):
        put(g, int(round(cx + math.cos(a) * rr)), int(round(cy + math.sin(a) * rr)), 'h')
    return outline(g)

def frostling(pose):
    """frostling 32 x 26 facing right: spiny ice hare. pose 0 idle, 1 crouch, 2 airborne"""
    W, H = 32, 26; g = blank(W, H); sq = [0, 3, -2][pose]
    cx, cy, rx, ry = 13.0, 15.0 + sq * 0.5, 11.0, 8.5 - sq * 0.4
    for y in range(H):
        for x in range(W):
            nx, ny = (x - cx) / rx, (y - cy) / ry
            if nx * nx + ny * ny <= 1: g[y][x] = shade(x, y, cx, cy, rx, ry)
    hx, hy = 24.0, 11.0 + sq * 0.6
    for y in range(H):
        for x in range(W):
            if (x - hx) ** 2 + (y - hy) ** 2 <= 30: g[y][x] = shade(x, y, hx, hy, 5.5, 5.5)
    for k in range(5):                    # crystal spines along the back
        sx = 6 + k * 4; top = int(cy - ry * math.sqrt(max(0.0, 1 - ((sx - cx) / rx) ** 2))) - 1
        for t in range(5 - (k % 2)): put(g, sx, top - t, 'E' if t < 3 else 'h'); put(g, sx + 1, top - t + 1, '3')
    line(g, 24, int(hy) - 4, 22, int(hy) - 11, 'E', 2); line(g, 27, int(hy) - 4, 29, int(hy) - 10, 'E', 2)     # ears
    put(g, 27, int(hy) - 1, 'h'); put(g, 28, int(hy) - 1, 'h'); put(g, 27, int(hy), 'e')
    for k in range(3): put(g, 29 + k, int(hy) + 2, '2')
    ly = int(cy + ry) - 1                  # legs
    if pose == 2:
        line(g, 6, ly, 3, ly + 3, '2', 3); line(g, 19, ly, 22, ly + 2, '2', 3)
    else:
        line(g, 7, ly, 5 + sq // 2, ly + 5 - sq // 2, '2', 3); line(g, 19, ly, 21 + sq // 2, ly + 5 - sq // 2, '2', 3)
    return outline(g)

def turret(open_):
    """shard turret 20 x 34: a crystal spire on a rock base; the tip glows when it is about to fire"""
    W, H = 20, 34; g = blank(W, H)
    for y in range(24, 34):                # rock base
        for x in range(1, 19):
            if abs(x - 10) <= 9 - (33 - y) * 0.0 - max(0, (y - 31)): g[y][x] = '3' if (x < 6 or y < 27) else '2' if x < 14 else '1'
    for (cx, top, hw) in ((10, 1, 4), (5, 9, 3), (15, 11, 3)):
        for y in range(top, 28):
            half = min(hw, (y - top) // 2 + (0 if y - top > 2 else 0))
            for dx in range(-half, half + 1):
                x = cx + dx
                if 0 <= x < W: g[y][x] = '4' if dx == -half and half > 0 else '3' if dx < 0 else '2' if dx < half else '1'
    for y in range(3, 10): put(g, 10, y, 'h' if open_ else 'E'); put(g, 9, y, 'E' if open_ else 'e')
    if open_:
        for dx in (-2, -1, 0, 1, 2): put(g, 10 + dx, 0, 'h')
    return outline(g)

if __name__ == '__main__':
    out = {'wisp': [wisp(i) for i in range(3)], 'frostling': [frostling(i) for i in range(3)], 'turret': [turret(False), turret(True)]}
    path = os.path.join(os.path.dirname(os.path.abspath(__file__)), '..', 'js', 'art', 'zone2foes.js')
    src = "/* GENERATED by tools/enemy_gen2.py: zone 2 enemy frames. */\n(function (G) {\n  G.art = G.art || {};\n  G.art.zone2foes = " + json.dumps(out, separators=(',', ':')) + ";\n})((window.SGS = window.SGS || {}));\n"
    open(path, 'w', encoding='utf-8').write(src)
    print('wrote', len(src))
