"""Composable hero: aim-angle torsos x lean variants and leg poses (10-frame run with a deep stride, skid, landing squash) -> js/art/hero2.js.
Torso + legs are layered at runtime (sprites.js) so every aim angle works while running, jumping or standing."""
import json, math, os, sys
sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
import hero_gen as H

ANGLES = {90: ((14, 15), (15, 2)), 70: ((14, 15), (19, 3)), 45: ((14, 16), (25, 7)), 20: ((14, 17), (27, 13)), -20: ((14, 18), (27, 22)), -45: ((15, 18), (26, 23)), -75: ((15, 18), (19, 24))}
TIPS = {90: (15, 2), 70: (19, 3), 45: (25, 7), 20: (27, 13), 0: (27, 18), -20: (27, 22), -45: (26, 23), -75: (19, 24)}
LEANS = [-2, 1, 2, 3, 4, 5, 6]

def top(angle, lean):
    base = H.body() if angle == 0 else H.with_arm(H.aim_arm(*ANGLES[angle]))
    g = [['.'] * H.CW for _ in range(25)]
    for y, r in enumerate(base):
        sh = H.lean_shift(y, lean)
        for x, c in enumerate(r):
            if c != '.' and 0 <= x + 1 + sh < H.CW: g[y][x + 1 + sh] = c
    return [''.join(r) for r in g]

def ik(hip, ank, L1=6.8, L2=6.8):
    """two-bone knee position, bending forward (+x)"""
    dx, dy = ank[0] - hip[0], ank[1] - hip[1]; d = max(0.01, min(math.hypot(dx, dy), L1 + L2 - 0.4))
    a = (d * d + L1 * L1 - L2 * L2) / (2 * d); h = math.sqrt(max(0.0, L1 * L1 - a * a)); ux, uy = dx / d, dy / d
    kx, ky = hip[0] + ux * a - uy * h, hip[1] + uy * a + ux * h
    if kx < hip[0] + (ank[0] - hip[0]) / 2 - 0.1: kx, ky = hip[0] + ux * a + uy * h, hip[1] + uy * a - ux * h
    return (max(0, min(H.CW - 1, int(round(kx)))), max(0, min(19, int(round(ky)))))

def stride(t, hx, hipy, reach=9, lift=7, ground=17):
    """leg phase t in [0,1): 0 = foot planted out in front, stance carries it back until 0.5, then swing brings it forward"""
    if t < 0.5:
        u = t / 0.5; ax = hx + reach - 2 * reach * u; ay = ground
    else:
        u = (t - 0.5) / 0.5; ax = hx - reach + 2 * reach * u; ay = ground - lift * math.sin(math.pi * u) ** 0.8
    return (int(round(ax)), int(round(ay)))

def legs2(a_ank, b_ank, hipy):
    """legs with the hips dropped to hipy (bent knees): a = front leg, b = back leg"""
    g = H.blank(20)
    for (hx, ank, front) in ((11, b_ank, False), (13, a_ank, True)):
        hip = (hx, hipy); k = ik(hip, ank)
        H.limb(g, hip, k, ank, front)
    g = H.outline(g)
    H.put(g, 0, 8, "o4332221111o"); H.put(g, 1, 8, "o3222111111o")
    for r in range(2, hipy + 1): H.put(g, r, 9, "o22111111o")
    return H.fin(g)

def pad(rows): return ['.' + r + '.' * (H.CW - H.W - 1) for r in rows]

def run_frames(n=10, hipy=7):
    out = []
    for i in range(n):
        t = i / float(n)
        out.append(pad(legs2(stride(t, 13, hipy), stride((t + 0.5) % 1.0, 11, hipy), hipy)))
    return out

def build():
    legs = {'idle': pad(H.legs(H.IDLE_LEGS)), 'jump': pad(H.legs(H.JUMP_LEGS)), 'fall': pad(H.legs(H.FALL_LEGS))}
    for i, f in enumerate(run_frames()): legs['run%d' % i] = f
    legs['skid'] = pad(legs2((20, 17), (15, 17), 6))
    legs['land'] = pad(legs2((19, 17), (6, 17), 10))
    legs['crouch'] = pad(legs2((19, 17), (8, 17), 12))        # deep squat: hips dropped, knees pushed forward
    tops = {}
    for a in [0] + sorted(ANGLES):
        for l in LEANS: tops['%d_%d' % (a, l)] = top(a, l)
    return {'legs': legs, 'top': tops, 'tips': {str(k): v for k, v in TIPS.items()}}

if __name__ == '__main__':
    out = build()
    path = os.path.join(os.path.dirname(os.path.abspath(__file__)), '..', 'js', 'art', 'hero2.js')
    src = "/* GENERATED by tools/hero_gen2.py: layered hero parts (torso per aim angle and lean, leg poses). */\n(function (G) {\n  G.art = G.art || {};\n  G.art.hero2 = " + json.dumps(out, separators=(',', ':')) + ";\n})((window.SGS = window.SGS || {}));\n"
    open(path, 'w', encoding='utf-8').write(src)
    print('wrote', len(src), 'tops', len(out['top']), 'legs', len(out['legs']))
