"""Writes js/rooms/sandbox.js: a dev test room that exercises slopes, ledges, tunnels, breakables, hazards and enemies."""
import json, os
W, H = 64, 17
g = [['.'] * W for _ in range(H)]
def rect(x0, y0, x1, y1, c):
    for y in range(y0, y1 + 1):
        for x in range(x0, x1 + 1):
            g[y][x] = c
rect(0, 15, W - 1, 16, '#'); rect(0, 0, 0, 16, '#'); rect(W - 1, 0, W - 1, 16, '#'); rect(0, 0, W - 1, 1, '#')
rect(38, 15, 41, 15, '^')                      # spike pit floor
g[14][10] = '/'; rect(11, 14, 16, 14, '#'); g[14][17] = chr(92)
rect(20, 11, 25, 11, '='); rect(27, 8, 32, 8, '=')
rect(45, 9, 47, 13, '#')                       # wall with a morph tunnel beneath
rect(49, 12, 49, 14, 'b'); rect(51, 14, 51, 14, 'B'); rect(53, 13, 53, 14, 'M')
rect(55, 11, 62, 11, '#'); rect(57, 12, 57, 14, '#')
rect(2, 12, 6, 12, '=')
for (x, y, c) in [(24, 14, 'c'), (34, 14, 'c'), (13, 13, 'c'), (22, 6, 'm'), (44, 5, 'm'), (60, 10, 'o'), (3, 14, 'P')]:
    g[y][x] = c
for y in range(2, 15):                          # back wall region (ruin interior) in the middle
    for x in range(18, 44):
        if g[y][x] == '.':
            g[y][x] = 'w'
rows = [''.join(r) for r in g]
assert all(len(r) == W for r in rows)
out = {'id': 'sandbox', 'name': 'Test Chamber', 'zone': 1, 'map': rows}
path = os.path.join(os.path.dirname(os.path.abspath(__file__)), '..', 'js', 'rooms', 'sandbox.js')
open(path, 'w', encoding='utf-8').write("/* Dev test room (generated by tools/sandbox_gen.py). */\n(function (G) {\n  G.rooms = G.rooms || {};\n  G.rooms.sandbox = " + json.dumps(out) + ";\n})((window.SGS = window.SGS || {}));\n")
print('ok')
