"""Writes js/art/zone1.js (autotiled stone/moss set). Run: python tools/tile_gen3.py"""
import json, os
from tile_gen2 import tile
out = {'edge': {}, 'diag': {}}
for m in range(16):
    out['edge'][m] = [tile(v, m) for v in range(3)]
for d in range(1, 16):
    out['diag'][d] = tile(0, 0, d)
here = os.path.dirname(os.path.abspath(__file__))
path = os.path.join(here, '..', 'js', 'art', 'zone1.js')
body = json.dumps(out, separators=(',', ':'))
src = "/* GENERATED by tools/tile_gen3.py: zone 1 (Crash Site) autotile grids; edge[mask][variant], diag[bits]. Mask bits N=1 E=2 S=4 W=8 are sides facing air. */\n(function (G) {\n  G.art = G.art || {};\n  G.art.zone1 = " + body + ";\n})((window.SGS = window.SGS || {}));\n"
open(path, 'w', encoding='utf-8').write(src)
print('wrote', path, len(src))
