"""Zone 3 extras: animated lava (body + surface, 4 frames) and the purple wave-beam crystal block -> js/art/zone3.js (key set 'world3'; wave block uses visor letters so it works in any zone)"""
import json, math, os
from tile_gen1 import W, grid, put

def lava(frame, top):
    g = grid('C')
    for y in range(W):
        for x in range(W):
            v = math.sin((x + frame * 4) * 0.55 + y * 0.35) + math.sin((x * 0.9 - frame * 2 + y) * 0.4)
            g[y][x] = 'E' if v > 1.45 else 'D' if v > 0.55 else 'C' if v > -0.7 else 'B'
    if top:
        for x in range(W):
            h = 2 + int(round(1.4 * math.sin((x + frame * 3) * 0.7)))
            for y in range(h): g[y][x] = '.'
            g[h][x] = 'F'
            if h + 1 < W: g[h + 1][x] = 'E' if (x + frame) % 3 else 'F'
            if (x + frame * 2) % 7 == 0 and h > 0: g[h - 1][x] = 'F'
    return [''.join(r) for r in g]

def wave_block():
    g = grid('x')
    for i in range(W):
        g[0][i] = 'V'; g[15][i] = 'q'; g[i][0] = 'V'; g[i][15] = 'q'
    for i in range(1, 15):
        g[1][i] = 'v'; g[14][i] = 'q'; g[i][1] = 'v'; g[i][14] = 'q'
    for y in range(3, 13):
        for x in range(3, 13):
            d = abs(x - 7.5) + abs(y - 7.5)
            if d < 7: g[y][x] = 'v' if d > 4 else 'V' if d > 2 else 'h'
    for k in range(4):
        put(g, 7 - k, 4 + k, 'h'); put(g, 8 + k, 4 + k, 'h')
    return [''.join(r) for r in g]

def dash_block():
    g = grid('M')
    for i in range(W):
        g[0][i] = 'L'; g[15][i] = 'z'; g[i][0] = 'l'; g[i][15] = 'M'
    for i in range(1, 15):
        g[1][i] = 'l'; g[14][i] = 'M'; g[i][1] = 'l'; g[i][14] = 'M'
    for y in range(3, 13):
        for x in range(3, 13): g[y][x] = 'z'
    for k in range(4):   # speed chevrons
        for (x, y, c) in ((4 + k * 2, 5 + k, 'Y'), (5 + k * 2, 5 + k, 'y'), (4 + k * 2, 10 - k, 'Y'), (5 + k * 2, 10 - k, 'y')):
            put(g, x, y, c)
    for (x, y) in ((6, 3), (9, 12), (3, 8), (12, 8)): put(g, x, y, 'k')
    return [''.join(r) for r in g]

if __name__ == '__main__':
    out = {'lava': [lava(f, False) for f in range(4)], 'lavaTop': [lava(f, True) for f in range(4)], 'wave': wave_block(), 'dashblock': dash_block()}
    path = os.path.join(os.path.dirname(os.path.abspath(__file__)), '..', 'js', 'art', 'zone3.js')
    src = "/* GENERATED by tools/tile_gen7.py: lava frames and the wave-beam block. */\n(function (G) {\n  G.art = G.art || {};\n  G.art.zone3 = " + json.dumps(out, separators=(',', ':')) + ";\n})((window.SGS = window.SGS || {}));\n"
    open(path, 'w', encoding='utf-8').write(src)
    print('wrote', len(src))
