"""Zone 2 (Cryo Vaults) extras: slippery ice floor tile, icicles, glowing crystal clusters -> js/art/zone2.js (compiled with the 'world2' key set)"""
import json, os
from tile_gen1 import W, grid, put

def ice():
    g = grid('D')
    for y in range(W):
        for x in range(W):
            d = (x + y) % 11
            if d == 0: g[y][x] = 'F'
            elif d == 1: g[y][x] = 'E'
            elif (x * 3 + y * 5) % 17 == 0: g[y][x] = 'C'
    for x in range(W):
        g[0][x] = 'F'; g[1][x] = 'E'; g[14][x] = 'C'; g[15][x] = 'B'
    for y in range(W):
        g[y][0] = 'E' if y not in (0, 15) else g[y][0]; g[y][15] = 'C' if y not in (0, 15) else g[y][15]
    for (x, y) in [(4, 5), (5, 6), (6, 7), (11, 9), (10, 10), (9, 11)]:
        g[y][x] = 'B'
    return [''.join(r) for r in g]

def icicle(n, w=7):
    g = [['.'] * w for _ in range(n)]
    for y in range(n):
        half = max(0.5, (w / 2.0) * (1 - y / float(n)))
        x0 = int(round(w / 2.0 - half)); x1 = int(round(w / 2.0 + half)) - 1
        for x in range(x0, max(x0, x1) + 1):
            if 0 <= x < w:
                t = (x - x0) / max(1.0, x1 - x0)
                g[y][x] = 'F' if t < 0.25 else 'E' if t < 0.55 else 'D' if t < 0.8 else 'C'
        g[y][x0] = 'F' if y % 5 else 'E'
        if y == 0:
            for x in range(w): g[0][x] = 'E' if x else 'F'
    for y in range(n):                  # selective outline on the shadow side
        for x in range(w - 1, -1, -1):
            if g[y][x] != '.':
                g[y][x] = 'B' if (x == w - 1 or g[y][x + 1] == '.') and y > 1 else g[y][x]
                break
    return [''.join(r) for r in g]

def crystal(heights):
    """a cluster of prisms (lit left face, dark right face) rising from a common base, glowing cyan"""
    Wc = 6 * len(heights) + 4; H = max(heights) + 3
    g = grid(Wc, H) if False else [['.'] * Wc for _ in range(H)]
    for i, h in enumerate(heights):
        cx = 4 + i * 6
        for y in range(h):
            half = 2 if y > 3 else max(0, y // 2)
            for dx in range(-half, half + 1):
                x = cx + dx; yy = H - 2 - h + y + 3
                if 0 <= yy < H and 0 <= x < Wc:
                    g[yy][x] = 'h' if dx == -half and half > 0 else 'E' if dx <= 0 else 'e' if dx < half else 'g'
        if H - 2 - h + 3 < H: g[H - 2 - h + 3][cx] = 'h'
    for x in range(Wc):
        g[H - 1][x] = 'd' if g[H - 2][x] != '.' else '.'
    out = [r[:] for r in g]
    for y in range(H):
        for x in range(Wc):
            if g[y][x] == '.':
                for dx, dy in ((1, 0), (-1, 0), (0, 1), (0, -1)):
                    xx, yy = x + dx, y + dy
                    if 0 <= xx < Wc and 0 <= yy < H and g[yy][xx] not in '.d': out[y][x] = 'd'; break
    return [''.join(r) for r in out]

if __name__ == '__main__':
    out = {'ice': ice(), 'icicle': [icicle(10), icicle(16), icicle(24, 9)], 'crystal': [crystal([14, 22, 10]), crystal([18, 9])]}
    path = os.path.join(os.path.dirname(os.path.abspath(__file__)), '..', 'js', 'art', 'zone2.js')
    src = "/* GENERATED by tools/tile_gen6.py: zone 2 ice floor tile, icicles, crystal clusters. */\n(function (G) {\n  G.art = G.art || {};\n  G.art.zone2 = " + json.dumps(out, separators=(',', ':')) + ";\n})((window.SGS = window.SGS || {}));\n"
    open(path, 'w', encoding='utf-8').write(src)
    print('wrote', len(src))
