"""Zone 1 slopes, spikes and breakable blocks -> js/art/zone1misc.js"""
import json, os
from tile_gen1 import W, grid, put, fill_tile

def slope(right):
    """45-degree slope tile: stone below the diagonal, moss draped along it. right=True rises to the right ('/')."""
    base = fill_tile(1)
    g = grid('.')
    for x in range(W):
        lx = x if right else 15 - x
        y0 = 16 - lx if right else 16 - lx   # first solid row for this column (surface y)
        y0 = 16 - lx
        for y in range(max(y0, 0), W):
            g[y][x] = base[y][x]
        if y0 < W:
            for k, c in enumerate(['E' if (x % 4) else 'F', 'D', 'C', 'B']):
                if y0 + k < W and (k < 3 or x % 3 == 0):
                    g[y0 + k][x] = c
            if y0 + 4 < W and g[y0 + 4][x] in '1234':
                g[y0 + 4][x] = '1'
    if not right:
        g = [r[::-1] for r in g]
        # mirror, keeping light from the upper left: flip highlight bias by swapping the lit rim to the new left edge
    return [''.join(r) for r in g]

def slope_mirror_fix(rows):
    return rows

SPIKES = [
    "................",
    "................",
    "..s.....s....s..",
    "..k.s...k...sk..",
    ".sky.k..y..skY..",
    ".kyYsky.ky.kyY..",
    ".kyYkyYskyskyY.s",
    "skyYkyYkykyYyYsk",
    "kyYYkyYYkykYYyYk",
    "kyYwkyYwkykYwyYk",
    "kyyYkyyYkykyYyYk",
    "0kyyk0kyk0kyykyk",
    "00kk0000k0000kk0",
    "1010101010101010",
    "0101010101010101",
    "0000000000000000",
]

def block_shot():
    g = [list(r) for r in fill_tile(2)]
    # sandy crumble block: earth ramp, visible cracks
    ramp = {'1': 'q', '2': 'r', '3': 't', '4': 'u', '5': 'u', 'B': 'r', 'C': 't'}
    g = [[ramp.get(c, c) for c in r] for r in g]
    for (x, y) in [(3, 2), (4, 3), (4, 4), (5, 5), (10, 9), (9, 10), (9, 11), (8, 12), (13, 3), (12, 4)]:
        g[y][x] = 'p'
    return [''.join(r) for r in g]

def block_bomb():
    g = [list(r) for r in fill_tile(0)]
    for (x, y, c) in [(7, 5, 'w'), (8, 5, 'Y'), (6, 6, 'Y'), (7, 6, 'w'), (8, 6, 'Y'), (9, 6, 'y'), (5, 7, 'y'), (6, 7, 'Y'), (7, 7, 'Y'), (8, 7, 'y'), (9, 7, 'y'), (10, 7, 'k'), (6, 8, 'y'), (7, 8, 'y'), (8, 8, 'y'), (9, 8, 'k'), (7, 9, 'k'), (8, 9, 'k')]:
        g[y][x] = c
    return [''.join(r) for r in g]

def block_missile():
    g = grid('m')
    for i in range(W):
        g[0][i] = 'L'; g[15][i] = 'z'; g[i][0] = 'l'; g[i][15] = 'M'
    for i in range(1, 15):
        g[1][i] = 'l'; g[14][i] = 'M'; g[i][1] = 'l'; g[i][14] = 'M'
    for (x, y) in [(2, 2), (13, 2), (2, 13), (13, 13)]:
        g[y][x] = 'z'
    for y in range(4, 12):
        for x in range(4, 12):
            g[y][x] = 'M'
    for k in range(4):   # red-gold chevrons
        for x in (6 + k, 9 - k):
            g[5 + k][x] = 'Y'; g[6 + k][x] = 'y'
    return [''.join(r) for r in g]

if __name__ == '__main__':
    sl, sr = slope(True), slope(False)
    out = {'slopeR': sl, 'slopeL': sr, 'spikes': SPIKES, 'blockShot': block_shot(), 'blockBomb': block_bomb(), 'blockMissile': block_missile()}
    for k, v in out.items():
        assert all(len(r) == 16 for r in v) and len(v) == 16, k
    path = os.path.join(os.path.dirname(os.path.abspath(__file__)), '..', 'js', 'art', 'zone1misc.js')
    src = "/* GENERATED by tools/tile_gen5.py: slopes, spikes and breakable blocks (16x16 grids). */\n(function (G) {\n  G.art = G.art || {};\n  G.art.zone1misc = " + json.dumps(out, separators=(',', ':')) + ";\n})((window.SGS = window.SGS || {}));\n"
    open(path, 'w', encoding='utf-8').write(src)
    print('wrote', len(src))
